name: Lint Commit Messages
on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    commitlint:
        runs-on: ubuntu-latest
        steps:
            - name: Configure Git
              run: |
                  git config --global user.name "GitHub Actions"
                  git config --global user.email "github-actions[bot]@users.noreply.github.com"

            - name: Checkout
              uses: actions/checkout@v3
              with:
                  ref: ${{ github.event.pull_request.head.sha }}
                  fetch-depth: 0

            - name: Install Commitlint
              uses: wagoid/commitlint-github-action@v5
              with:
                  configFile: commitlint.config.js

            - name: Run Commitlint
              uses: wagoid/commitlint-github-action@v5
              with:
                  configFile: commitlint.config.js
                  edit: ${{ github.event_name == 'pull_request' }}
                  failOnErrors: true
